apiVersion: vmoperator.vmware.com/v1alpha1
kind: VirtualMachine
metadata:
  labels:
    vm.name: db-vm
    role: db
  name: mysql-db
  namespace: namespace-1
spec:
  imageName: ubuntu-22.04
  className: best-effort-small
  powerState: poweredOn
  storageClass: k8s-storage-policy
  networkInterfaces:
  - networkName:
    networkType: nsx-t
  vmMetadata:
      configMapName: mysql-db-cm
      transport: CloudInit
---
apiVersion: v1
kind: ConfigMap
metadata:
    name: mysql-db-cm
    namespace: namespace-1
data:
  user-data: >-
    CiNjbG91ZC1jb25maWcKCnNzaF9wd2F1dGg6IHRydWUKCmdyb3VwczoKICAtIGFkbWluZ3JvdXA6IFtyb290LHN5c10KCnVzZXJzOgogIC0gbmFtZTogZGV2CiAgICBnZWNvczogRGV2IFMuIE9wcwogICAgbG9ja19wYXNzd2Q6IGZhbHNlCiAgICBwYXNzd2Q6ICQ2JG4vekp1eS54L08wb1JLSHAkc1JLMHdObUtrVFJYMjZwb1JUVlBJc1hpejR1OVN2VlIyZXV6TlY3WlhSOURURC5MM1hnSDBUZ1paeXhpR0UxTXcuQjZEOFljcUNyTHB3RENvUm5CUS4gCiAgICBzdWRvOiBBTEw9KEFMTCkgTk9QQVNTV0Q6QUxMCiAgICBncm91cHM6IHN1ZG8sIHVzZXJzLCBhZG1pbgogICAgc2hlbGw6IC9iaW4vYmFzaAoKd3JpdGVfZmlsZXM6CiAgLSBjb250ZW50OiB8CiAgICAgICBBTFRFUiBVU0VSICdyb290J0AnbG9jYWxob3N0JyBJREVOVElGSUVEIFdJVEggbXlzcWxfbmF0aXZlX3Bhc3N3b3JkIEJZICdwYXNzd29yZCc7CiAgICBhcHBlbmQ6IHRydWUKICAgIHBhdGg6IC9hbHRlcnVzZXIudHh0CgogIC0gY29udGVudDogfAogICAgICAgQ1JFQVRFIFVTRVIgJ2Rldm9wcydAJyUnIElERU5USUZJRUQgV0lUSCBteXNxbF9uYXRpdmVfcGFzc3dvcmQgQlkgJ3Bhc3N3b3JkJzsKICAgICAgIENSRUFURSBEQVRBQkFTRSBkZW1vOwogICAgICAgR1JBTlQgQUxMIFBSSVZJTEVHRVMgT04gZGVtby4qIFRPICdkZXZvcHMnQCclJzsKCiAgICAgICBDUkVBVEUgVEFCTEUgZGVtby51c2VyICgKICAgICAgICAgaWQgSU5URUdFUiBQUklNQVJZIEtFWSBBVVRPX0lOQ1JFTUVOVCwKICAgICAgICAgdXNlcm5hbWUgdmFyY2hhcigyNTUpIE5PVCBOVUxMLAogICAgICAgICBwYXNzd29yZCB2YXJjaGFyKDI1NSkgTk9UIE5VTEwsCiAgICAgICAgIFVOSVFVRSAodXNlcm5hbWUpCiAgICAgICApOwoKCiAgICAgICBDUkVBVEUgVEFCTEUgZGVtby5lbnRyeSAoCiAgICAgICAgIGlkIElOVEVHRVIgUFJJTUFSWSBLRVkgQVVUT19JTkNSRU1FTlQsCiAgICAgICAgIGF1dGhvcl9pZCBJTlRFR0VSIE5PVCBOVUxMLAogICAgICAgICBjcmVhdGVkIFRJTUVTVEFNUCBOT1QgTlVMTCBERUZBVUxUIENVUlJFTlRfVElNRVNUQU1QLAogICAgICAgICB0aXRsZSB2YXJjaGFyKDI1NSkgTk9UIE5VTEwsCiAgICAgICAgIGJvZHkgdmFyY2hhcig1NDAwKSBOT1QgTlVMTCwKICAgICAgICAgRk9SRUlHTiBLRVkgKGF1dGhvcl9pZCkgUkVGRVJFTkNFUyB1c2VyIChpZCkKICAgICAgICk7CgogICAgICAgSU5TRVJUIElOVE8gZGVtby51c2VyICh1c2VybmFtZSxwYXNzd29yZCkgVkFMVUVTKCdKZXJlbXknLCdkZXZvcHMxMjMnKTsKICAgICAgIElOU0VSVCBJTlRPIGRlbW8uZW50cnkgKGF1dGhvcl9pZCx0aXRsZSxib2R5KSBWQUxVRVMoMSwiV2VsY29tZSB0byB0aGUgcmVxdWVzdCBwYWdlLCB0aGlzIGlzIHRoZSBmaXJzdCBlbnRyeSIsIlRoaXMgZW50cnkgaXMgb3duZWQgYnkgSmVyZW15IGFuZCBjYW4gb25seSBiZSBtb2RpZmllZCBieSBoaW0uIFlvdSBjYW4gY3JlYXRlIHlvdXIgb3duIHBvc3QgYnkgcmVnaXN0ZXJpbmcgYW5kIGxvZ2dpbmcgaW4hIik7CgogICAgYXBwZW5kOiB0cnVlCiAgICBwYXRoOiAvaW5pdC5zcWwKCnJ1bmNtZDoKICAtIHN1ZG8gYXB0IHVwZGF0ZQogIC0gc3VkbyBhcHQgLXkgaW5zdGFsbCBteXNxbC1zZXJ2ZXIKICAtIHN1ZG8gc3lzdGVtY3RsIHN0YXJ0IG15c3FsLnNlcnZpY2UKICAtIHN1ZG8gbXlzcWwgPCAvYWx0ZXJ1c2VyLnR4dAogIC0gbXlzcWwgLXUgcm9vdCAtcHBhc3N3b3JkIDwgL2luaXQuc3FsCiAgLSBzdWRvIHNlZCAtaSAnMCwvYmluZC1hZGRyZXNzL3MvLyNiaW5kLWFkZHJlc3MvJyAvZXRjL215c3FsL215c3FsLmNvbmYuZC9teXNxbGQuY25mCiAgLSBzdWRvIHN5c3RlbWN0bCByZXN0YXJ0IG15c3FsLnNlcnZpY2UK
---
apiVersion: vmoperator.vmware.com/v1alpha1
kind: VirtualMachineService
metadata:
  name: mysql-db
  namespace: namespace-1
spec:
  ports:
  - name: ssh
    port: 22
    protocol: TCP
    targetPort: 22
  - name: mysql
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    vm.name: db-vm
  type: LoadBalancer