apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config-volume
          mountPath: /usr/share/nginx/html
      volumes:
      - name: nginx-config-volume
        configMap:
          name: nginx-config
      imagePullSecrets:
      - name: docker-hub-creds
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>VCF Experience Day</title>
        <style>
            body {
                font-family: Arial, sans-serif;
                background-color: #f5f5f5;
                color: #333;
                margin: 0;
                padding: 0;
                line-height: 1.6;
            }
            .container {
                max-width: 800px;
                margin: 20px auto;
                padding: 0 20px;
            }
            h1 {
                color: #007db8;
                text-align: center;
            }
            p {
                margin-bottom: 20px;
            }
            a {
                color: #007db8;
                text-decoration: none;
            }
            a:hover {
                text-decoration: underline;
            }
        </style>
    </head>
    <body>
        <div class="container">
            <h1>Hello and welcome to VCF Experience Day!</h1>
            <p>The VCF Experience Program is a customer-focused, expert-led VCF workshops which provides structured education and direct hands-on with live VCF labs. Currently, Discovery Day provides attendees the opportunity to explore different use cases that show the power of running VCF. Our VCF and SDN Ninja Workshops will focus in on how to operate a VCF environment for those use cases and get deeper into the how to get started operationalizing VCF to support those use cases.</p>
            <p>You have previously deployed a MySQL database using VM Service, now let's see if you can connect to it! Follow this <a href="http:192.168.30.51:8080">link</a> to open an Adminer, a tool that will allow you to connect. Enter your MySQL IP, database, username, and password and click connect.</p>
            <p>We hope you have enjoyed this experience. To learn more about the features, and to get more hands-on experience, we encourage you to continue with the Ninja workshop.</p>
        </div>
    </body>
    </html>
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: nginx